# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.cache/wt [current_project]
set_property parent.project_path C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/instructions_mem.mem
read_verilog -library xil_defaultlib {
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/mux2.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/dflipflop.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/UART_receiver_switch.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/defines.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/shifter.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/PC_register.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/decoder32.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/muxarray.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/Four_Digit_Seven_Segment_Driver_Optimized.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/shift_one.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/multiple_keys.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/single_memory.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/rv32_ImmGen.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/RippleCarryAdder.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/RegFile.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/prv32_ALU.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/mux_4x1_four.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/mux_4x1.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/forwardingUnit.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/control_unit.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/branchOutput.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/ALU_control_unit.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/N_bit_register.v
  C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/sources_1/new/RISCVHandler.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/constrs_1/new/my_contraint.xdc
set_property used_in_implementation false [get_files C:/Users/CSE.CAL/Desktop/MS4_with_FPGA/MS4_with_FPGA/MS4/MS4.srcs/constrs_1/new/my_contraint.xdc]


synth_design -top RISCVHandler -part xc7a100tcsg324-1


write_checkpoint -force -noxdef RISCVHandler.dcp

catch { report_utilization -file RISCVHandler_utilization_synth.rpt -pb RISCVHandler_utilization_synth.pb }
